// this class was generated by a tool on Tue Apr 04 14:22:07 EDT 2006

package com.oy.shared.lm.graph.bo;

public abstract class BaseInfo implements java.io.Serializable {

  public static class Fields {
      public static final String caption = "caption";
      public static final String fillColor = "fillColor";
      public static final String lineColor = "lineColor";
      public static final String fontColor = "fontColor";
      public static final String fontSize = "fontSize";
      public static final String fontName = "fontName";
      public static final String attributes = "attributes";
  }

  public static class Relations {
  }

  public static class Columns {
      public static final String caption = "";
      public static final String fillColor = "";
      public static final String lineColor = "";
      public static final String fontColor = "";
      public static final String fontSize = "";
      public static final String fontName = "";
      public static final String attributes = "";
  }

  private String caption;
  private String fillColor;
  private String lineColor;
  private String fontColor;
  private double fontSize;
  private String fontName;
  private String attributes;



  public String getCaption (){
    return this.caption;
  }

  public void setCaption (String caption){
    this.caption = caption;
  }

  public String getFillColor (){
    return this.fillColor;
  }

  public void setFillColor (String fillColor){
    this.fillColor = fillColor;
  }

  public String getLineColor (){
    return this.lineColor;
  }

  public void setLineColor (String lineColor){
    this.lineColor = lineColor;
  }

  public String getFontColor (){
    return this.fontColor;
  }

  public void setFontColor (String fontColor){
    this.fontColor = fontColor;
  }

  public double getFontSize (){
    return this.fontSize;
  }

  public void setFontSize (double fontSize){
    this.fontSize = fontSize;
  }

  public String getFontName (){
    return this.fontName;
  }

  public void setFontName (String fontName){
    this.fontName = fontName;
  }

  public String getAttributes (){
    return this.attributes;
  }

  public void setAttributes (String attributes){
    this.attributes = attributes;
  }


  public void copyFieldsFrom(com.oy.shared.lm.graph.bo.BaseInfo source) {
    this.caption = source.caption;
    this.fillColor = source.fillColor;
    this.lineColor = source.lineColor;
    this.fontColor = source.fontColor;
    this.fontSize = source.fontSize;
    this.fontName = source.fontName;
    this.attributes = source.attributes;
  }
}
