// this class was generated by a tool on Tue Apr 04 14:22:07 EDT 2006

package com.oy.shared.lm.graph.bo;

public class EdgeInfo extends com.oy.shared.lm.graph.bo.BaseInfo implements java.io.Serializable {

  public static class Fields {
      public static final String headCaption = "headCaption";
      public static final String tailCaption = "tailCaption";
      public static final String mode = "mode";
      public static final String labelAngle = "labelAngle";
      public static final String labelDistance = "labelDistance";
      public static final String arrowSize = "arrowSize";
      public static final String arrowHead = "arrowHead";
      public static final String arrowTail = "arrowTail";
  }

  public static class Relations {
  }

  public static class Columns {
      public static final String headCaption = "";
      public static final String tailCaption = "";
      public static final String mode = "";
      public static final String labelAngle = "";
      public static final String labelDistance = "";
      public static final String arrowSize = "";
      public static final String arrowHead = "";
      public static final String arrowTail = "";
  }

  private String headCaption;
  private String tailCaption;
  private int mode;
  private double labelAngle;
  private double labelDistance;
  private double arrowSize;
  private int arrowHead;
  private int arrowTail;



  public String getHeadCaption (){
    return this.headCaption;
  }

  public void setHeadCaption (String headCaption){
    this.headCaption = headCaption;
  }

  public String getTailCaption (){
    return this.tailCaption;
  }

  public void setTailCaption (String tailCaption){
    this.tailCaption = tailCaption;
  }

  public int getMode (){
    return this.mode;
  }

  public void setMode (int mode){
    this.mode = mode;
  }

  public double getLabelAngle (){
    return this.labelAngle;
  }

  public void setLabelAngle (double labelAngle){
    this.labelAngle = labelAngle;
  }

  public double getLabelDistance (){
    return this.labelDistance;
  }

  public void setLabelDistance (double labelDistance){
    this.labelDistance = labelDistance;
  }

  public double getArrowSize (){
    return this.arrowSize;
  }

  public void setArrowSize (double arrowSize){
    this.arrowSize = arrowSize;
  }

  public int getArrowHead (){
    return this.arrowHead;
  }

  public void setArrowHead (int arrowHead){
    this.arrowHead = arrowHead;
  }

  public int getArrowTail (){
    return this.arrowTail;
  }

  public void setArrowTail (int arrowTail){
    this.arrowTail = arrowTail;
  }


  public static class ModeEnum {
      public static final int SOLID = 0;
      public static final int DASHED = 1;
      public static final int DOTTED = 2;
      public static final int BOLD = 3;
  }

  public boolean isModeSolid() {
    return mode == ModeEnum.SOLID;
  }
  public void setModeSolid() {
    mode = ModeEnum.SOLID;
  }
  public boolean isModeDashed() {
    return mode == ModeEnum.DASHED;
  }
  public void setModeDashed() {
    mode = ModeEnum.DASHED;
  }
  public boolean isModeDotted() {
    return mode == ModeEnum.DOTTED;
  }
  public void setModeDotted() {
    mode = ModeEnum.DOTTED;
  }
  public boolean isModeBold() {
    return mode == ModeEnum.BOLD;
  }
  public void setModeBold() {
    mode = ModeEnum.BOLD;
  }

  public static class ArrowHeadEnum {
      public static final int NORMAL = 0;
      public static final int ONORMAL = 1;
      public static final int DIAMOND = 2;
      public static final int ODIAMOND = 3;
      public static final int DOT = 4;
      public static final int ODOT = 5;
      public static final int NONE = 6;
  }

  public boolean isArrowHeadNormal() {
    return arrowHead == ArrowHeadEnum.NORMAL;
  }
  public void setArrowHeadNormal() {
    arrowHead = ArrowHeadEnum.NORMAL;
  }
  public boolean isArrowHeadOnormal() {
    return arrowHead == ArrowHeadEnum.ONORMAL;
  }
  public void setArrowHeadOnormal() {
    arrowHead = ArrowHeadEnum.ONORMAL;
  }
  public boolean isArrowHeadDiamond() {
    return arrowHead == ArrowHeadEnum.DIAMOND;
  }
  public void setArrowHeadDiamond() {
    arrowHead = ArrowHeadEnum.DIAMOND;
  }
  public boolean isArrowHeadOdiamond() {
    return arrowHead == ArrowHeadEnum.ODIAMOND;
  }
  public void setArrowHeadOdiamond() {
    arrowHead = ArrowHeadEnum.ODIAMOND;
  }
  public boolean isArrowHeadDot() {
    return arrowHead == ArrowHeadEnum.DOT;
  }
  public void setArrowHeadDot() {
    arrowHead = ArrowHeadEnum.DOT;
  }
  public boolean isArrowHeadOdot() {
    return arrowHead == ArrowHeadEnum.ODOT;
  }
  public void setArrowHeadOdot() {
    arrowHead = ArrowHeadEnum.ODOT;
  }
  public boolean isArrowHeadNone() {
    return arrowHead == ArrowHeadEnum.NONE;
  }
  public void setArrowHeadNone() {
    arrowHead = ArrowHeadEnum.NONE;
  }

  public static class ArrowTailEnum {
      public static final int NORMAL = 0;
      public static final int ONORMAL = 1;
      public static final int DIAMOND = 2;
      public static final int ODIAMOND = 3;
      public static final int DOT = 4;
      public static final int ODOT = 5;
      public static final int NONE = 6;
  }

  public boolean isArrowTailNormal() {
    return arrowTail == ArrowTailEnum.NORMAL;
  }
  public void setArrowTailNormal() {
    arrowTail = ArrowTailEnum.NORMAL;
  }
  public boolean isArrowTailOnormal() {
    return arrowTail == ArrowTailEnum.ONORMAL;
  }
  public void setArrowTailOnormal() {
    arrowTail = ArrowTailEnum.ONORMAL;
  }
  public boolean isArrowTailDiamond() {
    return arrowTail == ArrowTailEnum.DIAMOND;
  }
  public void setArrowTailDiamond() {
    arrowTail = ArrowTailEnum.DIAMOND;
  }
  public boolean isArrowTailOdiamond() {
    return arrowTail == ArrowTailEnum.ODIAMOND;
  }
  public void setArrowTailOdiamond() {
    arrowTail = ArrowTailEnum.ODIAMOND;
  }
  public boolean isArrowTailDot() {
    return arrowTail == ArrowTailEnum.DOT;
  }
  public void setArrowTailDot() {
    arrowTail = ArrowTailEnum.DOT;
  }
  public boolean isArrowTailOdot() {
    return arrowTail == ArrowTailEnum.ODOT;
  }
  public void setArrowTailOdot() {
    arrowTail = ArrowTailEnum.ODOT;
  }
  public boolean isArrowTailNone() {
    return arrowTail == ArrowTailEnum.NONE;
  }
  public void setArrowTailNone() {
    arrowTail = ArrowTailEnum.NONE;
  }

  public void copyFieldsFrom(com.oy.shared.lm.graph.bo.EdgeInfo source) {
    this.headCaption = source.headCaption;
    this.tailCaption = source.tailCaption;
    this.mode = source.mode;
    this.labelAngle = source.labelAngle;
    this.labelDistance = source.labelDistance;
    this.arrowSize = source.arrowSize;
    this.arrowHead = source.arrowHead;
    this.arrowTail = source.arrowTail;
  }
}
