// this class was generated by a tool on Tue Apr 04 14:22:07 EDT 2006

package com.oy.shared.lm.graph.bo;

public class GraphEdgeBean implements java.io.Serializable {

  public static class Fields {
      public static final String edgeId = "edgeId";
      public static final String graphId = "graphId";
      public static final String infoId = "infoId";
      public static final String fromNodeId = "fromNodeId";
      public static final String toNodeId = "toNodeId";
  }

  public static class Relations {
      public static final String Graph = "Graph";
      public static final String info = "info";
      public static final String fromNode = "fromNode";
      public static final String toNode = "toNode";
  }

  public static class Columns {
      public static final String edgeId = "";
      public static final String graphId = "";
      public static final String infoId = "";
      public static final String fromNodeId = "";
      public static final String toNodeId = "";
  }

  private int edgeId;
  private int graphId;
  private int infoId;
  private int fromNodeId;
  private int toNodeId;

  private com.oy.shared.lm.graph.bo.GraphBean Graph;
  private com.oy.shared.lm.graph.bo.EdgeInfo info;
  private com.oy.shared.lm.graph.bo.GraphNodeBean fromNode;
  private com.oy.shared.lm.graph.bo.GraphNodeBean toNode;


  public int getEdgeId (){
    return this.edgeId;
  }

  public void setEdgeId (int edgeId){
    this.edgeId = edgeId;
  }

  public int getGraphId (){
    return this.graphId;
  }

  public void setGraphId (int graphId){
    this.graphId = graphId;
  }

  public int getInfoId (){
    return this.infoId;
  }

  public void setInfoId (int infoId){
    this.infoId = infoId;
  }

  public int getFromNodeId (){
    return this.fromNodeId;
  }

  public void setFromNodeId (int fromNodeId){
    this.fromNodeId = fromNodeId;
  }

  public int getToNodeId (){
    return this.toNodeId;
  }

  public void setToNodeId (int toNodeId){
    this.toNodeId = toNodeId;
  }


  public void setGraph (com.oy.shared.lm.graph.bo.GraphBean Graph){
    this.Graph = Graph;
  }

  public com.oy.shared.lm.graph.bo.GraphBean getGraph (){
    return (com.oy.shared.lm.graph.bo.GraphBean) this.Graph;
  }

  public void setInfo (com.oy.shared.lm.graph.bo.EdgeInfo info){
    this.info = info;
  }

  public com.oy.shared.lm.graph.bo.EdgeInfo getInfo (){
    return (com.oy.shared.lm.graph.bo.EdgeInfo) this.info;
  }

  public void setFromNode (com.oy.shared.lm.graph.bo.GraphNodeBean fromNode){
    this.fromNode = fromNode;
  }

  public com.oy.shared.lm.graph.bo.GraphNodeBean getFromNode (){
    return (com.oy.shared.lm.graph.bo.GraphNodeBean) this.fromNode;
  }

  public void setToNode (com.oy.shared.lm.graph.bo.GraphNodeBean toNode){
    this.toNode = toNode;
  }

  public com.oy.shared.lm.graph.bo.GraphNodeBean getToNode (){
    return (com.oy.shared.lm.graph.bo.GraphNodeBean) this.toNode;
  }

  public void copyFieldsFrom(com.oy.shared.lm.graph.bo.GraphEdgeBean source) {
    this.edgeId = source.edgeId;
    this.graphId = source.graphId;
    this.infoId = source.infoId;
    this.fromNodeId = source.fromNodeId;
    this.toNodeId = source.toNodeId;
  }
}
