// this class was generated by a tool on Tue Apr 04 14:22:07 EDT 2006

package com.oy.shared.lm.graph.bo;

public class GraphBean implements java.io.Serializable {

  public static class Fields {
      public static final String infoId = "infoId";
  }

  public static class Relations {
      public static final String info = "info";
      public static final String nodes = "nodes";
      public static final String edges = "edges";
      public static final String groups = "groups";
  }

  public static class Columns {
      public static final String infoId = "";
  }

  private int infoId;

  private com.oy.shared.lm.graph.bo.GraphInfo info;
  private java.util.Collection nodes;
  private java.util.Collection edges;
  private java.util.Collection groups;


  public int getInfoId (){
    return this.infoId;
  }

  public void setInfoId (int infoId){
    this.infoId = infoId;
  }


  public void setInfo (com.oy.shared.lm.graph.bo.GraphInfo info){
    this.info = info;
  }

  public com.oy.shared.lm.graph.bo.GraphInfo getInfo (){
    return (com.oy.shared.lm.graph.bo.GraphInfo) this.info;
  }

  public void setNodes (java.util.Collection nodes){
    this.nodes = nodes;
  }

  public java.util.Collection getNodes (){
    return (java.util.Collection) this.nodes;
  }

  public void setEdges (java.util.Collection edges){
    this.edges = edges;
  }

  public java.util.Collection getEdges (){
    return (java.util.Collection) this.edges;
  }

  public void setGroups (java.util.Collection groups){
    this.groups = groups;
  }

  public java.util.Collection getGroups (){
    return (java.util.Collection) this.groups;
  }

  public void copyFieldsFrom(com.oy.shared.lm.graph.bo.GraphBean source) {
    this.infoId = source.infoId;
  }
}
