// this class was generated by a tool on Tue Apr 04 14:22:07 EDT 2006

package com.oy.shared.lm.graph.bo;

public class GraphInfo extends com.oy.shared.lm.graph.bo.BaseInfo implements java.io.Serializable {

  public static class Fields {
      public static final String rotated = "rotated";
      public static final String nodeAttributes = "nodeAttributes";
      public static final String edgeAttributes = "edgeAttributes";
  }

  public static class Relations {
  }

  public static class Columns {
      public static final String rotated = "";
      public static final String nodeAttributes = "";
      public static final String edgeAttributes = "";
  }

  private boolean rotated;
  private String nodeAttributes;
  private String edgeAttributes;



  public boolean getRotated (){
    return this.rotated;
  }

  public void setRotated (boolean rotated){
    this.rotated = rotated;
  }

  public String getNodeAttributes (){
    return this.nodeAttributes;
  }

  public void setNodeAttributes (String nodeAttributes){
    this.nodeAttributes = nodeAttributes;
  }

  public String getEdgeAttributes (){
    return this.edgeAttributes;
  }

  public void setEdgeAttributes (String edgeAttributes){
    this.edgeAttributes = edgeAttributes;
  }


  public void copyFieldsFrom(com.oy.shared.lm.graph.bo.GraphInfo source) {
    this.rotated = source.rotated;
    this.nodeAttributes = source.nodeAttributes;
    this.edgeAttributes = source.edgeAttributes;
  }
}
