// this class was generated by a tool on Tue Apr 04 14:22:07 EDT 2006

package com.oy.shared.lm.graph.bo;

public class NodeInfo extends com.oy.shared.lm.graph.bo.BaseInfo implements java.io.Serializable {

  public static class Fields {
      public static final String header = "header";
      public static final String footer = "footer";
      public static final String shape = "shape";
      public static final String mode = "mode";
      public static final String filled = "filled";
      public static final String rounded = "rounded";
  }

  public static class Relations {
  }

  public static class Columns {
      public static final String header = "";
      public static final String footer = "";
      public static final String shape = "";
      public static final String mode = "";
      public static final String filled = "";
      public static final String rounded = "";
  }

  private String header;
  private String footer;
  private int shape;
  private int mode;
  private boolean filled;
  private boolean rounded;



  public String getHeader (){
    return this.header;
  }

  public void setHeader (String header){
    this.header = header;
  }

  public String getFooter (){
    return this.footer;
  }

  public void setFooter (String footer){
    this.footer = footer;
  }

  public int getShape (){
    return this.shape;
  }

  public void setShape (int shape){
    this.shape = shape;
  }

  public int getMode (){
    return this.mode;
  }

  public void setMode (int mode){
    this.mode = mode;
  }

  public boolean getFilled (){
    return this.filled;
  }

  public void setFilled (boolean filled){
    this.filled = filled;
  }

  public boolean getRounded (){
    return this.rounded;
  }

  public void setRounded (boolean rounded){
    this.rounded = rounded;
  }


  public static class ShapeEnum {
      public static final int RECORD = 0;
      public static final int BOX = 1;
      public static final int ELLIPSE = 2;
      public static final int CIRCLE = 3;
      public static final int DIAMOND = 4;
      public static final int TRIANGLE = 5;
      public static final int INVTRIANGLE = 6;
      public static final int HEXAGON = 7;
      public static final int OCTAGON = 8;
      public static final int PARALLELOGRAM = 9;
  }

  public boolean isShapeRecord() {
    return shape == ShapeEnum.RECORD;
  }
  public void setShapeRecord() {
    shape = ShapeEnum.RECORD;
  }
  public boolean isShapeBox() {
    return shape == ShapeEnum.BOX;
  }
  public void setShapeBox() {
    shape = ShapeEnum.BOX;
  }
  public boolean isShapeEllipse() {
    return shape == ShapeEnum.ELLIPSE;
  }
  public void setShapeEllipse() {
    shape = ShapeEnum.ELLIPSE;
  }
  public boolean isShapeCircle() {
    return shape == ShapeEnum.CIRCLE;
  }
  public void setShapeCircle() {
    shape = ShapeEnum.CIRCLE;
  }
  public boolean isShapeDiamond() {
    return shape == ShapeEnum.DIAMOND;
  }
  public void setShapeDiamond() {
    shape = ShapeEnum.DIAMOND;
  }
  public boolean isShapeTriangle() {
    return shape == ShapeEnum.TRIANGLE;
  }
  public void setShapeTriangle() {
    shape = ShapeEnum.TRIANGLE;
  }
  public boolean isShapeInvtriangle() {
    return shape == ShapeEnum.INVTRIANGLE;
  }
  public void setShapeInvtriangle() {
    shape = ShapeEnum.INVTRIANGLE;
  }
  public boolean isShapeHexagon() {
    return shape == ShapeEnum.HEXAGON;
  }
  public void setShapeHexagon() {
    shape = ShapeEnum.HEXAGON;
  }
  public boolean isShapeOctagon() {
    return shape == ShapeEnum.OCTAGON;
  }
  public void setShapeOctagon() {
    shape = ShapeEnum.OCTAGON;
  }
  public boolean isShapeParallelogram() {
    return shape == ShapeEnum.PARALLELOGRAM;
  }
  public void setShapeParallelogram() {
    shape = ShapeEnum.PARALLELOGRAM;
  }

  public static class ModeEnum {
      public static final int SOLID = 0;
      public static final int DASHED = 1;
      public static final int DOTTED = 2;
      public static final int BOLD = 3;
  }

  public boolean isModeSolid() {
    return mode == ModeEnum.SOLID;
  }
  public void setModeSolid() {
    mode = ModeEnum.SOLID;
  }
  public boolean isModeDashed() {
    return mode == ModeEnum.DASHED;
  }
  public void setModeDashed() {
    mode = ModeEnum.DASHED;
  }
  public boolean isModeDotted() {
    return mode == ModeEnum.DOTTED;
  }
  public void setModeDotted() {
    mode = ModeEnum.DOTTED;
  }
  public boolean isModeBold() {
    return mode == ModeEnum.BOLD;
  }
  public void setModeBold() {
    mode = ModeEnum.BOLD;
  }

  public void copyFieldsFrom(com.oy.shared.lm.graph.bo.NodeInfo source) {
    this.header = source.header;
    this.footer = source.footer;
    this.shape = source.shape;
    this.mode = source.mode;
    this.filled = source.filled;
    this.rounded = source.rounded;
  }
}
